export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SIGNUP_USER = 'SIGNUP_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const  LOG_OUT = ' LOG_OUT';
