export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SIGNUP_USER = 'SIGNUP_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
